# Generated by Django 4.0.dev20220124055124 on 2024-04-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('food', 'Food'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=100)),
            ],
        ),
    ]
